name = "IsApprox"
uuid = "28f27b66-4bd8-47e7-9110-e2746eb8bed7"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com>"]
version = "2.0.0"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"

[compat]
Aqua = ">= 0.8"
Dictionaries = "0.2, 0.3, 0.4"
JET = ">= 0.0"
LinearAlgebra = ">= 0.0"
PrecompileTools = "1"
Test = ">= 0.0"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "JET"]
