name = "IsApprox"
uuid = "28f27b66-4bd8-47e7-9110-e2746eb8bed7"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
