name = "IsApprox"
uuid = "28f27b66-4bd8-47e7-9110-e2746eb8bed7"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com>"]
version = "0.1.5"

[deps]
DictTools = "6033591e-aae9-4c88-8f5f-a341f9ca5325"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
