name = "IsApprox"
uuid = "28f27b66-4bd8-47e7-9110-e2746eb8bed7"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com>"]
version = "0.1.6"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Dictionaries = "0.2, 0.3"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
